-- MySQL Script generated by MySQL Workbench
-- Sun 10 Feb 2019 01:30:37 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Lavadero
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Lavadero` ;

-- -----------------------------------------------------
-- Schema Lavadero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lavadero` DEFAULT CHARACTER SET utf8 ;
USE `Lavadero` ;

-- -----------------------------------------------------
-- Table `Lavadero`.`Propietarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lavadero`.`Propietarios` ;

CREATE TABLE IF NOT EXISTS `Lavadero`.`Propietarios` (
  `id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lavadero`.`Trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lavadero`.`Trabajador` ;

CREATE TABLE IF NOT EXISTS `Lavadero`.`Trabajador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lavadero`.`Modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lavadero`.`Modelo` ;

CREATE TABLE IF NOT EXISTS `Lavadero`.`Modelo` (
  `Nombre` VARCHAR(100) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Marca` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lavadero`.`Lavados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lavadero`.`Lavados` ;

CREATE TABLE IF NOT EXISTS `Lavadero`.`Lavados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(45) NULL DEFAULT NULL,
  `Modelo` VARCHAR(100) NULL,
  `Hora` TIME NULL DEFAULT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Propietarios_id` VARCHAR(45) NULL DEFAULT NULL,
  `Trabajador_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lavados_Propietarios_idx` (`Propietarios_id` ASC),
  INDEX `fk_Lavados_Trabajador1_idx` (`Trabajador_id` ASC),
  INDEX `fk_Lavados_Modelo1_idx` (`Modelo` ASC),
  CONSTRAINT `fk_Lavados_Propietarios`
    FOREIGN KEY (`Propietarios_id`)
    REFERENCES `Lavadero`.`Propietarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavados_Trabajador1`
    FOREIGN KEY (`Trabajador_id`)
    REFERENCES `Lavadero`.`Trabajador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavados_Modelo1`
    FOREIGN KEY (`Modelo`)
    REFERENCES `Lavadero`.`Modelo` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

